// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignUpRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	RoleType             int32    `protobuf:"varint,3,opt,name=roleType,proto3" json:"roleType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SignUpRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *SignUpRequest) GetRoleType() int32 {
	if m != nil {
		return m.RoleType
	}
	return 0
}

type SignUpResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type SignInRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SignInRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type SignInResponse struct {
	// AccountInfo accountInfo = 1;
	SessionInfo          *SessionInfo `protobuf:"bytes,2,opt,name=sessionInfo,proto3" json:"sessionInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetSessionInfo() *SessionInfo {
	if m != nil {
		return m.SessionInfo
	}
	return nil
}

type AccountInfo struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Pwd                  string   `protobuf:"bytes,5,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Remark               string   `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Address              string   `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	PrivilegeId          int32    `protobuf:"varint,10,opt,name=privilegeId,proto3" json:"privilegeId,omitempty"`
	RoleId               int32    `protobuf:"varint,11,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Stat                 string   `protobuf:"bytes,12,opt,name=stat,proto3" json:"stat,omitempty"`
	LlTime               string   `protobuf:"bytes,13,opt,name=llTime,proto3" json:"llTime,omitempty"`
	CTime                string   `protobuf:"bytes,14,opt,name=cTime,proto3" json:"cTime,omitempty"`
	ChangeTime           string   `protobuf:"bytes,15,opt,name=changeTime,proto3" json:"changeTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (m *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(m, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AccountInfo) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *AccountInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AccountInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *AccountInfo) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *AccountInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AccountInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AccountInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AccountInfo) GetPrivilegeId() int32 {
	if m != nil {
		return m.PrivilegeId
	}
	return 0
}

func (m *AccountInfo) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *AccountInfo) GetStat() string {
	if m != nil {
		return m.Stat
	}
	return ""
}

func (m *AccountInfo) GetLlTime() string {
	if m != nil {
		return m.LlTime
	}
	return ""
}

func (m *AccountInfo) GetCTime() string {
	if m != nil {
		return m.CTime
	}
	return ""
}

func (m *AccountInfo) GetChangeTime() string {
	if m != nil {
		return m.ChangeTime
	}
	return ""
}

// TODO session的消息体
type SessionInfo struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	AccountId            string   `protobuf:"bytes,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	TTL                  string   `protobuf:"bytes,4,opt,name=TTL,proto3" json:"TTL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionInfo) Reset()         { *m = SessionInfo{} }
func (m *SessionInfo) String() string { return proto.CompactTextString(m) }
func (*SessionInfo) ProtoMessage()    {}
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *SessionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionInfo.Unmarshal(m, b)
}
func (m *SessionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionInfo.Marshal(b, m, deterministic)
}
func (m *SessionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionInfo.Merge(m, src)
}
func (m *SessionInfo) XXX_Size() int {
	return xxx_messageInfo_SessionInfo.Size(m)
}
func (m *SessionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SessionInfo proto.InternalMessageInfo

func (m *SessionInfo) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SessionInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SessionInfo) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *SessionInfo) GetTTL() string {
	if m != nil {
		return m.TTL
	}
	return ""
}

type SignOutRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutRequest) Reset()         { *m = SignOutRequest{} }
func (m *SignOutRequest) String() string { return proto.CompactTextString(m) }
func (*SignOutRequest) ProtoMessage()    {}
func (*SignOutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *SignOutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutRequest.Unmarshal(m, b)
}
func (m *SignOutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutRequest.Marshal(b, m, deterministic)
}
func (m *SignOutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutRequest.Merge(m, src)
}
func (m *SignOutRequest) XXX_Size() int {
	return xxx_messageInfo_SignOutRequest.Size(m)
}
func (m *SignOutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutRequest proto.InternalMessageInfo

func (m *SignOutRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type SignOutResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutResponse) Reset()         { *m = SignOutResponse{} }
func (m *SignOutResponse) String() string { return proto.CompactTextString(m) }
func (*SignOutResponse) ProtoMessage()    {}
func (*SignOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *SignOutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutResponse.Unmarshal(m, b)
}
func (m *SignOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutResponse.Marshal(b, m, deterministic)
}
func (m *SignOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutResponse.Merge(m, src)
}
func (m *SignOutResponse) XXX_Size() int {
	return xxx_messageInfo_SignOutResponse.Size(m)
}
func (m *SignOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutResponse proto.InternalMessageInfo

func (m *SignOutResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*SignUpRequest)(nil), "proto.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "proto.SignUpResponse")
	proto.RegisterType((*SignInRequest)(nil), "proto.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "proto.SignInResponse")
	proto.RegisterType((*AccountInfo)(nil), "proto.AccountInfo")
	proto.RegisterType((*SessionInfo)(nil), "proto.SessionInfo")
	proto.RegisterType((*SignOutRequest)(nil), "proto.SignOutRequest")
	proto.RegisterType((*SignOutResponse)(nil), "proto.SignOutResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x6e, 0x9c, 0x3a, 0x3f, 0x63, 0x92, 0xa2, 0x55, 0xa9, 0x56, 0x51, 0x85, 0x22, 0x9f, 0xca,
	0x25, 0x87, 0x82, 0x84, 0x84, 0xc4, 0x81, 0x0b, 0x92, 0x25, 0x04, 0x92, 0x13, 0x0e, 0x1c, 0x8d,
	0x3d, 0xa4, 0xab, 0x3a, 0xbb, 0xc6, 0x6b, 0xb7, 0xe2, 0xe5, 0x78, 0x29, 0x5e, 0x00, 0xed, 0xec,
	0x6e, 0xec, 0xf8, 0xd0, 0x43, 0x4f, 0xbb, 0xdf, 0xf7, 0xcd, 0xdf, 0xce, 0xce, 0xc0, 0x22, 0xcb,
	0x73, 0xd5, 0xca, 0x66, 0x53, 0xd5, 0xaa, 0x51, 0x2c, 0xa4, 0x23, 0xfe, 0x01, 0x8b, 0xad, 0xd8,
	0xcb, 0xef, 0x55, 0x8a, 0xbf, 0x5b, 0xd4, 0x0d, 0x5b, 0xc1, 0xac, 0xd5, 0x58, 0x7f, 0xcd, 0x0e,
	0xc8, 0x47, 0xeb, 0xd1, 0xcd, 0x3c, 0x3d, 0x62, 0xf6, 0x12, 0xc6, 0xd5, 0x63, 0xc1, 0x03, 0xa2,
	0xcd, 0xd5, 0x58, 0xd7, 0xaa, 0xc4, 0xdd, 0x9f, 0x0a, 0xf9, 0x78, 0x3d, 0xba, 0x09, 0xd3, 0x23,
	0x8e, 0x37, 0xb0, 0xf4, 0xa1, 0x75, 0xa5, 0xa4, 0x46, 0x76, 0x0d, 0x73, 0x8d, 0x5a, 0x0b, 0x25,
	0x93, 0xc2, 0x05, 0xef, 0x88, 0xf8, 0xa3, 0x2d, 0x25, 0x91, 0xcf, 0x2a, 0x25, 0xfe, 0x6c, 0xd3,
	0x19, 0x77, 0x97, 0xee, 0x1d, 0x44, 0x3e, 0xba, 0xfc, 0xa5, 0xc8, 0x36, 0xba, 0x65, 0xf6, 0xfd,
	0x9b, 0x6d, 0xa7, 0xa4, 0x7d, 0xb3, 0xf8, 0x5f, 0x00, 0xd1, 0x27, 0xdb, 0x2a, 0x83, 0xd9, 0x12,
	0x02, 0x61, 0xab, 0x0d, 0xd3, 0x40, 0x14, 0x94, 0x59, 0xd8, 0xcc, 0x61, 0x6a, 0xae, 0x27, 0x75,
	0x8e, 0x07, 0x75, 0xae, 0x60, 0x26, 0x45, 0x7e, 0x2f, 0x8d, 0x76, 0x6e, 0x35, 0x8f, 0xfd, 0x1b,
	0xc2, 0xae, 0x9d, 0x97, 0x10, 0xe2, 0x21, 0x13, 0x25, 0x9f, 0x10, 0x67, 0x81, 0x61, 0xab, 0x3b,
	0x25, 0x91, 0x4f, 0x2d, 0x4b, 0x80, 0x5d, 0xc1, 0xa4, 0xc6, 0x43, 0x56, 0xdf, 0xf3, 0x19, 0xd1,
	0x0e, 0x31, 0x0e, 0xd3, 0xac, 0x28, 0x6a, 0xd4, 0x9a, 0xcf, 0x49, 0xf0, 0x90, 0xad, 0x21, 0xaa,
	0x6a, 0xf1, 0x20, 0x4a, 0xdc, 0x63, 0x52, 0x70, 0xa0, 0x17, 0xf4, 0x29, 0x8a, 0xa9, 0x4a, 0x23,
	0x46, 0x24, 0x3a, 0xc4, 0x18, 0x9c, 0xeb, 0x26, 0x6b, 0xf8, 0x0b, 0x0a, 0x48, 0x77, 0x63, 0x5b,
	0x96, 0x3b, 0x71, 0x40, 0xbe, 0xb0, 0xf9, 0x2d, 0x32, 0xd5, 0xe6, 0x44, 0x2f, 0x6d, 0xb5, 0x04,
	0xd8, 0x6b, 0x80, 0xfc, 0x2e, 0x93, 0x7b, 0x24, 0xe9, 0x82, 0xa4, 0x1e, 0x13, 0x3f, 0x42, 0xd4,
	0xfb, 0x91, 0xa7, 0x27, 0xe5, 0xa4, 0xe1, 0xc1, 0xa0, 0xe1, 0xd7, 0x30, 0x77, 0x83, 0x9e, 0x14,
	0xee, 0x37, 0x3a, 0xc2, 0xb4, 0x7c, 0xb7, 0xfb, 0xe2, 0x7e, 0xc2, 0x5c, 0xfd, 0x94, 0x7e, 0x6b,
	0x1b, 0x3f, 0x76, 0x4f, 0x4f, 0xe9, 0x1b, 0xb8, 0x38, 0xda, 0xbb, 0x39, 0xa3, 0x9f, 0xd0, 0x6d,
	0xd9, 0x90, 0xf5, 0x2c, 0x75, 0xe8, 0xf6, 0xef, 0x08, 0x96, 0x6e, 0x92, 0xb6, 0x58, 0x3f, 0x88,
	0x1c, 0xd9, 0x7b, 0x98, 0xd8, 0x9d, 0x60, 0x97, 0x7e, 0x0e, 0xfb, 0xdb, 0xb7, 0x7a, 0x35, 0x60,
	0x6d, 0x86, 0xf8, 0xcc, 0x3b, 0x26, 0xf2, 0xc4, 0xf1, 0xb8, 0x2b, 0x27, 0x8e, 0xdd, 0x0a, 0xc4,
	0x67, 0xec, 0x03, 0x4c, 0x5d, 0xbd, 0xac, 0x6f, 0xd3, 0xbd, 0x77, 0x75, 0x35, 0xa4, 0xbd, 0xef,
	0xcf, 0x09, 0x09, 0x6f, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x49, 0x00, 0x3d, 0x0c, 0x3b, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	// 注册
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
	// 登录
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	// 退出
	SignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*SignOutResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*SignOutResponse, error) {
	out := new(SignOutResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/SignOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	// 注册
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
	// 登录
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	// 退出
	SignOut(context.Context, *SignOutRequest) (*SignOutResponse, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) SignUp(ctx context.Context, req *SignUpRequest) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedAccountServiceServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedAccountServiceServer) SignOut(ctx context.Context, req *SignOutRequest) (*SignOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignOut not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/SignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SignOut(ctx, req.(*SignOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _AccountService_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _AccountService_SignIn_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _AccountService_SignOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
