// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-05-21 11:54:18.4613938 +0800 CST m=+0.160009201

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "jimi co ptt platform web api.",
        "title": "JiMi Web API",
        "contact": {},
        "license": {},
        "version": "1.0.1"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "创建下级账户",
                "parameters": [
                    {
                        "description": "创建下级账户所用的信息",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.CreateAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true,\"account_id\": 1430 }",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/account/info/update": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "更新下级账户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新下级账户的信息，其中id和loginId和NickName不能为空",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.AccountUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": \"true\",\"msg\":\"update account success\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/account/login.do/{account_name}": {
            "post": {
                "description": "login by account name and pwd",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "elephant",
                        "name": "account_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "登录信息，username和pwd必填",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Account"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":\"true\",\"session_id\": sId }",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/account/logout.do/{account_name}": {
            "post": {
                "description": "logout by account name and pwd, 请求头中Authorization参数设置为登录时返回的sessionId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "退出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "登录信息，username和pwd必填",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Account"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":\"true\",\"msg\": \"SignOut is successful\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/account/pwd/update": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "更新用户密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新用户密码",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.AccountPwd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"result\": \"success\",\"msg\":\"Password changed successfully\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/account/{account_name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取账户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前用户的账号",
                        "name": "account_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"User information obtained successfully\",\t\"account_info\": ai,\t\"device_list\" deviceAll,\"group_list\": gList,\"tree_data\":resp}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/account_class/{accountId}/{searchId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取账户下级目录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前用户的账号Id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "获取用户下级目录的账号Id",
                        "name": "searchId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"User information obtained successfully\",\t\"account_info\": ai,\t\"device_list\" deviceAll,\"group_list\": gList,\"tree_data\":resp}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/account_device/{accountId}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "转移设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "当前用户的账号Id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "转移设备的model",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.AccountDeviceTransReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"result\": \"success\",\"msg\":\"Password changed successfully\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/account_device/{accountId}/{getAdviceId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取账户的设备信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前用户的账号Id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "获取用户设备信息的账号Id",
                        "name": "getAdviceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"User information obtained successfully\",\t\"account_info\": ai,\t\"device_list\" deviceAll,\"group_list\": gList,\"tree_data\":resp}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/device/import/{account_name}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "导入设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "当前用户的账号",
                        "name": "account_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "导入设备的model",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.AccountImportDeviceReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"result\": \"success\",\"msg\":\"Password changed successfully\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/device/update": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "更新设备信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "当前用户的账号",
                        "name": "account_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新设备信息的model",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.DeviceUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"result\": \"success\",\"msg\":\"Password changed successfully\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/im-server/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "websocket与grpc交换数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前用户的账号Id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"User information obtained successfully\",\t\"account_info\": ai,\t\"device_list\" deviceAll,\"group_list\": gList,\"tree_data\":resp}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "model.ImMsgData",
                        "description": "上传文件携带的参数",
                        "name": "fileInfo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"User information obtained successfully\",\t\"account_info\": ai,\t\"device_list\" deviceAll,\"group_list\": gList,\"tree_data\":resp}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Account": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "c_time": {
                    "type": "string"
                },
                "change_time": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ll_time": {
                    "type": "string"
                },
                "nick_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "pid": {
                    "type": "integer"
                },
                "privilege_id": {
                    "type": "integer"
                },
                "pwd": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "elephant"
                }
            }
        },
        "model.AccountDeviceTransReq": {
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Device"
                    }
                },
                "receiver": {
                    "type": "object",
                    "$ref": "#/definitions/model.DeviceReceiver"
                },
                "sender": {
                    "type": "object",
                    "$ref": "#/definitions/model.Account"
                }
            }
        },
        "model.AccountImportDeviceReq": {
            "type": "object",
            "properties": {
                "d_type": {
                    "type": "string"
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Device"
                    }
                }
            }
        },
        "model.AccountPwd": {
            "type": "object",
            "properties": {
                "confirm_pwd": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "new_pwd": {
                    "type": "string"
                },
                "old_pwd": {
                    "type": "string"
                }
            }
        },
        "model.AccountUpdate": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "login_id": {
                    "type": "string"
                },
                "nick_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "type_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.CreateAccount": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "c_time": {
                    "type": "string"
                },
                "change_time": {
                    "type": "string"
                },
                "confirm_pwd": {
                    "type": "string",
                    "example": "111111"
                },
                "contact": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 5
                },
                "ll_time": {
                    "type": "string"
                },
                "nick_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "pid": {
                    "type": "integer"
                },
                "privilege_id": {
                    "type": "integer"
                },
                "pwd": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.Device": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "active_time": {
                    "type": "string"
                },
                "change_time": {
                    "type": "string"
                },
                "course": {
                    "type": "number"
                },
                "create_time": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "gps_data": {
                    "type": "object",
                    "$ref": "#/definitions/model.GPS"
                },
                "id": {
                    "type": "integer"
                },
                "imei": {
                    "type": "string"
                },
                "last_login_time": {
                    "type": "string"
                },
                "local_time": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "sale_time": {
                    "type": "string"
                },
                "speed": {
                    "type": "number"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "model.DeviceReceiver": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "account_name": {
                    "type": "string"
                }
            }
        },
        "model.DeviceUpdate": {
            "type": "object",
            "properties": {
                "ActiveTime": {
                    "type": "string"
                },
                "ChangeTime": {
                    "type": "string"
                },
                "CreateTime": {
                    "type": "string"
                },
                "DeviceType": {
                    "type": "string"
                },
                "IMei": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "LLTime": {
                    "type": "string"
                },
                "LocalTime": {
                    "type": "integer"
                },
                "LoginId": {
                    "type": "integer"
                },
                "NickName": {
                    "type": "string"
                },
                "SaleTime": {
                    "type": "string"
                }
            }
        },
        "model.GPS": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
