basePath: '{{.BasePath}}'
definitions:
  model.Account:
    properties:
      address:
        type: string
      c_time:
        type: string
      change_time:
        type: string
      contact:
        type: string
      email:
        type: string
      id:
        type: integer
      ll_time:
        type: string
      nick_name:
        type: string
      phone:
        type: string
      pid:
        type: integer
      privilege_id:
        type: integer
      pwd:
        example: "123456"
        type: string
      remark:
        type: string
      role_id:
        type: integer
      state:
        type: string
      username:
        example: elephant
        type: string
    required:
    - username
    type: object
  model.AccountDeviceTransReq:
    properties:
      devices:
        items:
          $ref: '#/definitions/model.Device'
        type: array
      receiver:
        $ref: '#/definitions/model.DeviceReceiver'
        type: object
      sender:
        $ref: '#/definitions/model.Account'
        type: object
    type: object
  model.AccountForSwag:
    properties:
      pwd:
        example: "123456"
        type: string
      username:
        example: elephant
        type: string
    required:
    - username
    type: object
  model.AccountImportDeviceReq:
    properties:
      d_type:
        type: string
      devices:
        items:
          $ref: '#/definitions/model.Device'
        type: array
    type: object
  model.AccountPwd:
    properties:
      confirm_pwd:
        type: string
      id:
        type: string
      new_pwd:
        type: string
      old_pwd:
        type: string
    type: object
  model.AccountUpdate:
    properties:
      address:
        type: string
      contact:
        type: string
      email:
        type: string
      id:
        type: string
      login_id:
        type: string
      nick_name:
        type: string
      phone:
        type: string
      remark:
        type: string
      type_id:
        type: string
      username:
        type: string
    type: object
  model.CreateAccountForSwag:
    properties:
      confirm_pwd:
        example: "111111"
        type: string
      nick_name:
        example: nickDis001
        type: string
      pid:
        example: 13
        type: integer
      pwd:
        example: "123456"
        type: string
      role_id:
        example: 3
        type: integer
      username:
        example: dis007
        type: string
    type: object
  model.Device:
    properties:
      account_id:
        type: integer
      active_time:
        type: string
      change_time:
        type: string
      course:
        type: number
      create_time:
        type: string
      device_type:
        type: string
      gps_data:
        $ref: '#/definitions/model.GPS'
        type: object
      id:
        type: integer
      imei:
        type: string
      last_login_time:
        type: string
      local_time:
        type: integer
      nick_name:
        type: string
      password:
        type: string
      sale_time:
        type: string
      speed:
        type: number
      user_name:
        type: string
    type: object
  model.DeviceReceiver:
    properties:
      account_id:
        type: integer
      account_name:
        type: string
    type: object
  model.DeviceUpdate:
    properties:
      ActiveTime:
        type: string
      ChangeTime:
        type: string
      CreateTime:
        type: string
      DeviceType:
        type: string
      IMei:
        type: string
      Id:
        type: integer
      LLTime:
        type: string
      LocalTime:
        type: integer
      LoginId:
        type: integer
      NickName:
        type: string
      SaleTime:
        type: string
    type: object
  model.GPS:
    properties:
      lat:
        type: number
      lng:
        type: number
    type: object
  model.GroupInfo:
    properties:
      account_id:
        type: integer
      c_time:
        type: string
      group_name:
        type: string
      id:
        type: integer
      online_num:
        type: integer
      status:
        type: string
    type: object
  model.GroupList:
    properties:
      device_ids:
        items:
          type: integer
        type: array
      device_infos:
        items:
          type: '&{%!s(token.Pos=1527) %!s(*ast.FieldList=&{1536 [] 1537}) %!s(bool=false)}'
        type: array
      group_info:
        $ref: '#/definitions/model.GroupInfo'
        type: object
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: jimi co ptt platform web api.
  license: {}
  title: JiMi Web API
  version: 1.0.1
paths:
  /account:
    post:
      parameters:
      - description: 创建下级账户所用的信息
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/model.CreateAccountForSwag'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"success": true,"account_id": 1430 }'
          schema:
            type: string
      summary: 创建下级账户
  /account/{account_name}:
    get:
      parameters:
      - description: 当前用户的账号
        in: path
        name: account_name
        required: true
        type: string
      - description: 登录时返回的sessionId
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: "{\"message\":\"User information obtained successfully\",\t\"account_info\":
            ai,\t\"device_list\" deviceAll,\"group_list\": gList,\"tree_data\":resp}"
          schema:
            type: string
      summary: 获取账户信息
  /account/info/update:
    post:
      parameters:
      - description: 登录时返回的sessionId
        in: header
        name: Authorization
        required: true
        type: string
      - description: 更新下级账户的信息，其中id和loginId和NickName不能为空
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/model.AccountUpdate'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"success": "true","msg":"update account success"}'
          schema:
            type: string
      summary: 更新下级账户信息
  /account/login.do/{account_name}:
    post:
      consumes:
      - application/json
      description: login by account name and pwd
      parameters:
      - description: 登录的用户名，eg：elephant
        in: path
        name: account_name
        required: true
        type: string
      - description: 登录信息，username和pwd必填
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.AccountForSwag'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"session_id": "1c2c46b8-f44a-4073-b219-d93d22dd2a43", "success":
            "true"}'
          schema:
            type: string
      summary: 登录
  /account/logout.do/{account_name}:
    post:
      consumes:
      - application/json
      description: logout by account name and pwd, 请求头中Authorization参数设置为登录时返回的sessionId
      parameters:
      - description: 登录时返回的sessionId eg:1c2c46b8-f44a-4073-b219-d93d22dd2a43
        in: header
        name: Authorization
        required: true
        type: string
      - description: 登录信息，username和pwd必填
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.AccountForSwag'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":"true","msg": "SignOut is successful"}'
          schema:
            type: string
      summary: 退出
  /account/pwd/update:
    post:
      parameters:
      - description: 登录时返回的sessionId
        in: header
        name: Authorization
        required: true
        type: string
      - description: 更新用户密码
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/model.AccountPwd'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"result": "success","msg":"Password changed successfully"}'
          schema:
            type: string
      summary: 更新用户密码
  /account_class/{accountId}/{searchId}:
    get:
      parameters:
      - description: 当前用户的账号Id
        in: path
        name: accountId
        required: true
        type: string
      - description: 获取用户下级目录的账号Id
        in: path
        name: searchId
        required: true
        type: string
      - description: 登录时返回的sessionId
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: "{\"message\":\"User information obtained successfully\",\t\"account_info\":
            ai,\t\"device_list\" deviceAll,\"group_list\": gList,\"tree_data\":resp}"
          schema:
            type: string
      summary: 获取账户下级目录
  /account_device/{accountId}:
    post:
      parameters:
      - description: 登录时返回的sessionId
        in: header
        name: Authorization
        required: true
        type: string
      - description: 当前用户的账号Id
        in: path
        name: accountId
        required: true
        type: string
      - description: 转移设备的model
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/model.AccountDeviceTransReq'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"result": "success","msg":"Password changed successfully"}'
          schema:
            type: string
      summary: 转移设备
  /account_device/{accountId}/{getAdviceId}:
    get:
      parameters:
      - description: 当前用户的账号Id
        in: path
        name: accountId
        required: true
        type: string
      - description: 获取用户设备信息的账号Id
        in: path
        name: getAdviceId
        required: true
        type: string
      - description: 登录时返回的sessionId
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: "{\"message\":\"User information obtained successfully\",\t\"account_info\":
            ai,\t\"device_list\" deviceAll,\"group_list\": gList,\"tree_data\":resp}"
          schema:
            type: string
      summary: 获取账户的设备信息
  /device/import/{account_name}:
    post:
      parameters:
      - description: 登录时返回的sessionId
        in: header
        name: Authorization
        required: true
        type: string
      - description: 当前用户的账号
        in: path
        name: account_name
        required: true
        type: string
      - description: 导入设备的model
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/model.AccountImportDeviceReq'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"result": "success","msg":"Password changed successfully"}'
          schema:
            type: string
      summary: 导入设备
  /device/update:
    post:
      parameters:
      - description: 登录时返回的sessionId
        in: header
        name: Authorization
        required: true
        type: string
      - description: 当前用户的账号
        in: path
        name: account_name
        required: true
        type: string
      - description: 更新设备信息的model
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/model.DeviceUpdate'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"result": "success","msg":"Password changed successfully"}'
          schema:
            type: string
      summary: 更新设备信息
  /group:
    post:
      consumes:
      - application/json
      description: web创建群组, 请求头中Authorization参数设置为登录时返回的sessionId
      parameters:
      - description: 登录时返回的sessionId
        in: header
        name: Authorization
        required: true
        type: string
      - description: 创建群组
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.GroupList'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":"true","msg": resUpd.ResultMsg.Msg}'
          schema:
            type: string
      summary: web创建群组
  /group/delete:
    post:
      consumes:
      - application/json
      description: web创建群组, 请求头中Authorization参数设置为登录时返回的sessionId
      parameters:
      - description: 登录时返回的sessionId
        in: header
        name: Authorization
        required: true
        type: string
      - description: web更新群组
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.GroupInfo'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":"true","msg": resUpd.ResultMsg.Msg}'
          schema:
            type: string
      summary: web群组删除，目前只更新群组名字
  /group/devices/update:
    post:
      consumes:
      - application/json
      description: logout by account name and pwd, 请求头中Authorization参数设置为登录时返回的sessionId
      parameters:
      - description: 登录时返回的sessionId
        in: header
        name: Authorization
        required: true
        type: string
      - description: 更新群组中的设备
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.GroupList'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":"true","msg": resUpd.ResultMsg.Msg}'
          schema:
            type: string
      summary: web更新群组中的设备
  /group/update:
    post:
      consumes:
      - application/json
      description: web创建群组, 请求头中Authorization参数设置为登录时返回的sessionId
      parameters:
      - description: 登录时返回的sessionId
        in: header
        name: Authorization
        required: true
        type: string
      - description: web更新群组
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.GroupInfo'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":"true","msg": resUpd.ResultMsg.Msg}'
          schema:
            type: string
      summary: web更新群组信息，目前只更新群组名字
  /im-server/:
    get:
      parameters:
      - description: 当前用户的账号Id
        in: path
        name: accountId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: "{\"message\":\"User information obtained successfully\",\t\"account_info\":
            ai,\t\"device_list\" deviceAll,\"group_list\": gList,\"tree_data\":resp}"
          schema:
            type: string
      summary: websocket与grpc交换数据
  /upload:
    post:
      parameters:
      - description: 上传文件携带的参数
        in: formData
        name: fileInfo
        required: true
        type: model.ImMsgData
      produces:
      - application/json
      responses:
        "200":
          description: "{\"message\":\"User information obtained successfully\",\t\"account_info\":
            ai,\t\"device_list\" deviceAll,\"group_list\": gList,\"tree_data\":resp}"
          schema:
            type: string
      summary: 上传文件
swagger: "2.0"
