// Code generated by protoc-gen-go. DO NOT EDIT.
// source: talk_cloud_model.proto

package talk_cloud

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 组
type Group struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupName            string   `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	AccountId            int32    `protobuf:"varint,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e22deedf62cfd44, []int{0}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Group) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Group) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 成员
type Member struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IMei                 string   `protobuf:"bytes,2,opt,name=iMei,proto3" json:"iMei,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	NickName             string   `protobuf:"bytes,4,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Pwd                  string   `protobuf:"bytes,5,opt,name=pwd,proto3" json:"pwd,omitempty"`
	UserType             int32    `protobuf:"varint,6,opt,name=userType,proto3" json:"userType,omitempty"`
	AccountId            int32    `protobuf:"varint,7,opt,name=accountId,proto3" json:"accountId,omitempty"`
	ParentId             string   `protobuf:"bytes,8,opt,name=parentId,proto3" json:"parentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e22deedf62cfd44, []int{1}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Member) GetIMei() string {
	if m != nil {
		return m.IMei
	}
	return ""
}

func (m *Member) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Member) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Member) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *Member) GetUserType() int32 {
	if m != nil {
		return m.UserType
	}
	return 0
}

func (m *Member) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Member) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

// 错误信息
type Result struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e22deedf62cfd44, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Group)(nil), "talk_cloud.Group")
	proto.RegisterType((*Member)(nil), "talk_cloud.Member")
	proto.RegisterType((*Result)(nil), "talk_cloud.Result")
}

func init() { proto.RegisterFile("talk_cloud_model.proto", fileDescriptor_7e22deedf62cfd44) }

var fileDescriptor_7e22deedf62cfd44 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x3f, 0x6b, 0xc3, 0x30,
	0x14, 0xc4, 0x71, 0x6c, 0xab, 0xce, 0x1b, 0x4a, 0xd1, 0x10, 0x44, 0xe8, 0x10, 0x3c, 0x65, 0xca,
	0xd2, 0x0f, 0x51, 0x3a, 0xa4, 0x83, 0xe9, 0x1e, 0x14, 0xe9, 0x11, 0x84, 0xed, 0x48, 0xe8, 0x0f,
	0xa5, 0xdf, 0xb1, 0x1f, 0xaa, 0xe8, 0xc5, 0x8e, 0x69, 0xbb, 0xdd, 0xdd, 0x0f, 0xfb, 0xde, 0x09,
	0x36, 0x51, 0x0e, 0xfd, 0x49, 0x0d, 0x36, 0xe9, 0xd3, 0x68, 0x35, 0x0e, 0x07, 0xe7, 0x6d, 0xb4,
	0x1c, 0x96, 0xbc, 0xed, 0xa1, 0x7e, 0xf5, 0x36, 0x39, 0xfe, 0x08, 0x2b, 0xa3, 0x45, 0xb1, 0x2b,
	0xf6, 0x75, 0xb7, 0x32, 0x9a, 0x3f, 0xc3, 0xfa, 0x92, 0xc1, 0xbb, 0x1c, 0x51, 0xac, 0x76, 0xc5,
	0x7e, 0xdd, 0x2d, 0x41, 0xa6, 0x52, 0x29, 0x9b, 0xae, 0xf1, 0x4d, 0x8b, 0x92, 0x3e, 0x5a, 0x02,
	0xbe, 0x01, 0x16, 0xa2, 0x8c, 0x29, 0x88, 0x8a, 0xd0, 0xe4, 0xda, 0xef, 0x02, 0xd8, 0x11, 0xc7,
	0x33, 0xfa, 0x7f, 0x75, 0x1c, 0x2a, 0x73, 0x44, 0x33, 0x35, 0x91, 0xe6, 0x5b, 0x68, 0x52, 0x40,
	0x4f, 0x17, 0x94, 0x94, 0xdf, 0x7d, 0x66, 0x57, 0xa3, 0x7a, 0x62, 0xd5, 0x8d, 0xcd, 0x9e, 0x3f,
	0x41, 0xe9, 0x3e, 0xb5, 0xa8, 0x29, 0xce, 0x72, 0xfe, 0xd3, 0xc7, 0x97, 0x43, 0xc1, 0xa8, 0xf3,
	0xee, 0x7f, 0x4f, 0x79, 0xf8, 0x3b, 0x65, 0x0b, 0x8d, 0x93, 0x1e, 0x09, 0x36, 0xb7, 0x9e, 0xd9,
	0xb7, 0x07, 0x60, 0x1d, 0x86, 0x34, 0xc4, 0x7c, 0xbd, 0xb2, 0x1a, 0x69, 0x4f, 0xd9, 0x91, 0xce,
	0x57, 0x8c, 0xe1, 0x32, 0x0d, 0xca, 0xf2, 0xcc, 0xe8, 0xf9, 0x5f, 0x7e, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x8d, 0x0e, 0xb6, 0xdd, 0x98, 0x01, 0x00, 0x00,
}
