// Code generated by protoc-gen-go. DO NOT EDIT.
// source: talk_cloud_location.proto

package talk_cloud

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReportDataReq struct {
	DataType             int32     `protobuf:"varint,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
	DeviceInfo           *Device   `protobuf:"bytes,2,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	LocationInfo         *Location `protobuf:"bytes,3,opt,name=locationInfo,proto3" json:"locationInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReportDataReq) Reset()         { *m = ReportDataReq{} }
func (m *ReportDataReq) String() string { return proto.CompactTextString(m) }
func (*ReportDataReq) ProtoMessage()    {}
func (*ReportDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{0}
}

func (m *ReportDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportDataReq.Unmarshal(m, b)
}
func (m *ReportDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportDataReq.Marshal(b, m, deterministic)
}
func (m *ReportDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportDataReq.Merge(m, src)
}
func (m *ReportDataReq) XXX_Size() int {
	return xxx_messageInfo_ReportDataReq.Size(m)
}
func (m *ReportDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReportDataReq proto.InternalMessageInfo

func (m *ReportDataReq) GetDataType() int32 {
	if m != nil {
		return m.DataType
	}
	return 0
}

func (m *ReportDataReq) GetDeviceInfo() *Device {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *ReportDataReq) GetLocationInfo() *Location {
	if m != nil {
		return m.LocationInfo
	}
	return nil
}

type Device struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceType           int32    `protobuf:"varint,2,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	Battery              int32    `protobuf:"varint,3,opt,name=battery,proto3" json:"battery,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{1}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Device) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *Device) GetBattery() int32 {
	if m != nil {
		return m.Battery
	}
	return 0
}

type Location struct {
	GpsInfo              *GPS         `protobuf:"bytes,1,opt,name=gpsInfo,proto3" json:"gpsInfo,omitempty"`
	BSInfo               *BaseStation `protobuf:"bytes,2,opt,name=bSInfo,proto3" json:"bSInfo,omitempty"`
	WifiInfo             *Wifi        `protobuf:"bytes,3,opt,name=wifiInfo,proto3" json:"wifiInfo,omitempty"`
	BtInfo               *BlueTooth   `protobuf:"bytes,4,opt,name=btInfo,proto3" json:"btInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{2}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetGpsInfo() *GPS {
	if m != nil {
		return m.GpsInfo
	}
	return nil
}

func (m *Location) GetBSInfo() *BaseStation {
	if m != nil {
		return m.BSInfo
	}
	return nil
}

func (m *Location) GetWifiInfo() *Wifi {
	if m != nil {
		return m.WifiInfo
	}
	return nil
}

func (m *Location) GetBtInfo() *BlueTooth {
	if m != nil {
		return m.BtInfo
	}
	return nil
}

type GPS struct {
	LocalTime            uint64   `protobuf:"varint,1,opt,name=localTime,proto3" json:"localTime,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Speed                int32    `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Course               int32    `protobuf:"varint,5,opt,name=course,proto3" json:"course,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPS) Reset()         { *m = GPS{} }
func (m *GPS) String() string { return proto.CompactTextString(m) }
func (*GPS) ProtoMessage()    {}
func (*GPS) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{3}
}

func (m *GPS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPS.Unmarshal(m, b)
}
func (m *GPS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPS.Marshal(b, m, deterministic)
}
func (m *GPS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPS.Merge(m, src)
}
func (m *GPS) XXX_Size() int {
	return xxx_messageInfo_GPS.Size(m)
}
func (m *GPS) XXX_DiscardUnknown() {
	xxx_messageInfo_GPS.DiscardUnknown(m)
}

var xxx_messageInfo_GPS proto.InternalMessageInfo

func (m *GPS) GetLocalTime() uint64 {
	if m != nil {
		return m.LocalTime
	}
	return 0
}

func (m *GPS) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *GPS) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GPS) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *GPS) GetCourse() int32 {
	if m != nil {
		return m.Course
	}
	return 0
}

type BaseStation struct {
	Country              string   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	FirstBs              int32    `protobuf:"varint,4,opt,name=firstBs,proto3" json:"firstBs,omitempty"`
	SecondBs             int32    `protobuf:"varint,5,opt,name=secondBs,proto3" json:"secondBs,omitempty"`
	ThirdBs              int32    `protobuf:"varint,6,opt,name=thirdBs,proto3" json:"thirdBs,omitempty"`
	FourthBs             int32    `protobuf:"varint,7,opt,name=fourthBs,proto3" json:"fourthBs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseStation) Reset()         { *m = BaseStation{} }
func (m *BaseStation) String() string { return proto.CompactTextString(m) }
func (*BaseStation) ProtoMessage()    {}
func (*BaseStation) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{4}
}

func (m *BaseStation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseStation.Unmarshal(m, b)
}
func (m *BaseStation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseStation.Marshal(b, m, deterministic)
}
func (m *BaseStation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseStation.Merge(m, src)
}
func (m *BaseStation) XXX_Size() int {
	return xxx_messageInfo_BaseStation.Size(m)
}
func (m *BaseStation) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseStation.DiscardUnknown(m)
}

var xxx_messageInfo_BaseStation proto.InternalMessageInfo

func (m *BaseStation) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *BaseStation) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *BaseStation) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *BaseStation) GetFirstBs() int32 {
	if m != nil {
		return m.FirstBs
	}
	return 0
}

func (m *BaseStation) GetSecondBs() int32 {
	if m != nil {
		return m.SecondBs
	}
	return 0
}

func (m *BaseStation) GetThirdBs() int32 {
	if m != nil {
		return m.ThirdBs
	}
	return 0
}

func (m *BaseStation) GetFourthBs() int32 {
	if m != nil {
		return m.FourthBs
	}
	return 0
}

// TODO 待定
type Wifi struct {
	FirstWifi            int32    `protobuf:"varint,1,opt,name=firstWifi,proto3" json:"firstWifi,omitempty"`
	SecondWifi           int32    `protobuf:"varint,2,opt,name=secondWifi,proto3" json:"secondWifi,omitempty"`
	ThirdWifi            int32    `protobuf:"varint,3,opt,name=thirdWifi,proto3" json:"thirdWifi,omitempty"`
	FourthWifi           int32    `protobuf:"varint,4,opt,name=fourthWifi,proto3" json:"fourthWifi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wifi) Reset()         { *m = Wifi{} }
func (m *Wifi) String() string { return proto.CompactTextString(m) }
func (*Wifi) ProtoMessage()    {}
func (*Wifi) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{5}
}

func (m *Wifi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wifi.Unmarshal(m, b)
}
func (m *Wifi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wifi.Marshal(b, m, deterministic)
}
func (m *Wifi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wifi.Merge(m, src)
}
func (m *Wifi) XXX_Size() int {
	return xxx_messageInfo_Wifi.Size(m)
}
func (m *Wifi) XXX_DiscardUnknown() {
	xxx_messageInfo_Wifi.DiscardUnknown(m)
}

var xxx_messageInfo_Wifi proto.InternalMessageInfo

func (m *Wifi) GetFirstWifi() int32 {
	if m != nil {
		return m.FirstWifi
	}
	return 0
}

func (m *Wifi) GetSecondWifi() int32 {
	if m != nil {
		return m.SecondWifi
	}
	return 0
}

func (m *Wifi) GetThirdWifi() int32 {
	if m != nil {
		return m.ThirdWifi
	}
	return 0
}

func (m *Wifi) GetFourthWifi() int32 {
	if m != nil {
		return m.FourthWifi
	}
	return 0
}

//TODO 待定
type BlueTooth struct {
	FirstBt              int32    `protobuf:"varint,1,opt,name=firstBt,proto3" json:"firstBt,omitempty"`
	SecondBt             int32    `protobuf:"varint,2,opt,name=secondBt,proto3" json:"secondBt,omitempty"`
	ThirdBt              int32    `protobuf:"varint,3,opt,name=thirdBt,proto3" json:"thirdBt,omitempty"`
	FourthBt             int32    `protobuf:"varint,4,opt,name=fourthBt,proto3" json:"fourthBt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlueTooth) Reset()         { *m = BlueTooth{} }
func (m *BlueTooth) String() string { return proto.CompactTextString(m) }
func (*BlueTooth) ProtoMessage()    {}
func (*BlueTooth) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{6}
}

func (m *BlueTooth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlueTooth.Unmarshal(m, b)
}
func (m *BlueTooth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlueTooth.Marshal(b, m, deterministic)
}
func (m *BlueTooth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlueTooth.Merge(m, src)
}
func (m *BlueTooth) XXX_Size() int {
	return xxx_messageInfo_BlueTooth.Size(m)
}
func (m *BlueTooth) XXX_DiscardUnknown() {
	xxx_messageInfo_BlueTooth.DiscardUnknown(m)
}

var xxx_messageInfo_BlueTooth proto.InternalMessageInfo

func (m *BlueTooth) GetFirstBt() int32 {
	if m != nil {
		return m.FirstBt
	}
	return 0
}

func (m *BlueTooth) GetSecondBt() int32 {
	if m != nil {
		return m.SecondBt
	}
	return 0
}

func (m *BlueTooth) GetThirdBt() int32 {
	if m != nil {
		return m.ThirdBt
	}
	return 0
}

func (m *BlueTooth) GetFourthBt() int32 {
	if m != nil {
		return m.FourthBt
	}
	return 0
}

type ReportDataResp struct {
	Res                  *Result  `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportDataResp) Reset()         { *m = ReportDataResp{} }
func (m *ReportDataResp) String() string { return proto.CompactTextString(m) }
func (*ReportDataResp) ProtoMessage()    {}
func (*ReportDataResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{7}
}

func (m *ReportDataResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportDataResp.Unmarshal(m, b)
}
func (m *ReportDataResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportDataResp.Marshal(b, m, deterministic)
}
func (m *ReportDataResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportDataResp.Merge(m, src)
}
func (m *ReportDataResp) XXX_Size() int {
	return xxx_messageInfo_ReportDataResp.Size(m)
}
func (m *ReportDataResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportDataResp.DiscardUnknown(m)
}

var xxx_messageInfo_ReportDataResp proto.InternalMessageInfo

func (m *ReportDataResp) GetRes() *Result {
	if m != nil {
		return m.Res
	}
	return nil
}

func init() {
	proto.RegisterType((*ReportDataReq)(nil), "talk_cloud.ReportDataReq")
	proto.RegisterType((*Device)(nil), "talk_cloud.Device")
	proto.RegisterType((*Location)(nil), "talk_cloud.Location")
	proto.RegisterType((*GPS)(nil), "talk_cloud.GPS")
	proto.RegisterType((*BaseStation)(nil), "talk_cloud.BaseStation")
	proto.RegisterType((*Wifi)(nil), "talk_cloud.Wifi")
	proto.RegisterType((*BlueTooth)(nil), "talk_cloud.BlueTooth")
	proto.RegisterType((*ReportDataResp)(nil), "talk_cloud.ReportDataResp")
}

func init() { proto.RegisterFile("talk_cloud_location.proto", fileDescriptor_24d4a30cba502519) }

var fileDescriptor_24d4a30cba502519 = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x4f, 0x8b, 0x13, 0x4f,
	0x10, 0xfd, 0x4d, 0xfe, 0x4c, 0x92, 0xda, 0x9f, 0xab, 0x36, 0xeb, 0x9a, 0x0d, 0x22, 0xcb, 0xe0,
	0x61, 0x05, 0x8d, 0x10, 0x41, 0x3c, 0xc7, 0x85, 0x28, 0x78, 0x08, 0x9d, 0x80, 0x27, 0x59, 0x26,
	0x33, 0x9d, 0xa4, 0xd9, 0xd9, 0xe9, 0xb1, 0xbb, 0xc6, 0x25, 0x57, 0xaf, 0x7e, 0x02, 0x3f, 0x8f,
	0x07, 0xbf, 0x96, 0xf4, 0xbf, 0x99, 0xce, 0xc1, 0xe3, 0xab, 0x57, 0xaf, 0xea, 0x55, 0x77, 0x75,
	0xc3, 0x05, 0xa6, 0xc5, 0xed, 0x4d, 0x56, 0x88, 0x3a, 0xbf, 0x29, 0x44, 0x96, 0x22, 0x17, 0xe5,
	0xb4, 0x92, 0x02, 0x05, 0x81, 0x96, 0x9a, 0x9c, 0x07, 0x69, 0x77, 0x22, 0x67, 0x85, 0xcd, 0x49,
	0x7e, 0x45, 0xf0, 0x80, 0xb2, 0x4a, 0x48, 0xbc, 0x4e, 0x31, 0xa5, 0xec, 0x1b, 0x99, 0xc0, 0x30,
	0x4f, 0x31, 0x5d, 0x1f, 0x2a, 0x36, 0x8e, 0x2e, 0xa3, 0xab, 0x3e, 0x6d, 0x30, 0x99, 0x01, 0xe4,
	0xec, 0x3b, 0xcf, 0xd8, 0xa7, 0x72, 0x2b, 0xc6, 0x9d, 0xcb, 0xe8, 0xea, 0x64, 0x46, 0xa6, 0x6d,
	0xe9, 0xe9, 0xb5, 0x61, 0x69, 0x90, 0x45, 0xde, 0xc3, 0xff, 0xde, 0x97, 0x51, 0x75, 0x8d, 0xea,
	0x2c, 0x54, 0x7d, 0x76, 0x3c, 0x3d, 0xca, 0x4c, 0x28, 0xc4, 0xb6, 0x1e, 0x39, 0x85, 0x0e, 0xcf,
	0x9d, 0x9b, 0x0e, 0xcf, 0xc9, 0x73, 0xef, 0xc3, 0xb8, 0xec, 0x98, 0x78, 0x10, 0x21, 0x63, 0x18,
	0x6c, 0x52, 0x44, 0x26, 0x0f, 0xa6, 0x5d, 0x9f, 0x7a, 0x98, 0xfc, 0x8e, 0x60, 0xe8, 0xdb, 0x91,
	0x97, 0x30, 0xd8, 0x55, 0xca, 0xb8, 0x8a, 0x8c, 0xab, 0x87, 0xa1, 0xab, 0xc5, 0x72, 0x45, 0x3d,
	0x4f, 0xde, 0x40, 0xbc, 0x59, 0x05, 0x53, 0x3f, 0x0d, 0x33, 0xe7, 0xa9, 0x62, 0x2b, 0xb4, 0x23,
	0xb8, 0x34, 0xf2, 0x0a, 0x86, 0xf7, 0x7c, 0xcb, 0x83, 0x91, 0x1f, 0x85, 0x92, 0x2f, 0x7c, 0xcb,
	0x69, 0x93, 0x41, 0x5e, 0x43, 0xbc, 0x41, 0x93, 0xdb, 0x33, 0xb9, 0x4f, 0x8e, 0xca, 0x17, 0x35,
	0x5b, 0x0b, 0x81, 0x7b, 0xea, 0x92, 0x92, 0x9f, 0x11, 0x74, 0x17, 0xcb, 0x15, 0x79, 0x06, 0x23,
	0x7d, 0x62, 0xc5, 0x9a, 0xdf, 0xd9, 0xcb, 0xea, 0xd1, 0x36, 0x60, 0xd9, 0x72, 0xc7, 0xb1, 0xce,
	0xed, 0x21, 0x45, 0xb4, 0x0d, 0xe8, 0x7b, 0x2e, 0x52, 0xb4, 0x64, 0xd7, 0x90, 0x0d, 0x26, 0x67,
	0xd0, 0x57, 0x15, 0x63, 0xb9, 0x71, 0xd3, 0xa7, 0x16, 0x90, 0x73, 0x88, 0x33, 0x51, 0x4b, 0xc5,
	0xc6, 0x7d, 0x13, 0x76, 0x28, 0xf9, 0x13, 0xc1, 0x49, 0x70, 0x04, 0xfa, 0xf4, 0x33, 0x51, 0x97,
	0x28, 0x0f, 0xc6, 0xd3, 0x88, 0x7a, 0xa8, 0x7b, 0x8a, 0x8a, 0xc9, 0x14, 0x85, 0x34, 0x86, 0x46,
	0xb4, 0xc1, 0xba, 0xba, 0x64, 0x3b, 0x2e, 0x4a, 0xe3, 0x66, 0x44, 0x1d, 0xd2, 0xd5, 0xb6, 0x5c,
	0x2a, 0x9c, 0x2b, 0xe7, 0xc6, 0x43, 0x5d, 0x4d, 0xb1, 0x4c, 0x94, 0xf9, 0x5c, 0x39, 0x47, 0x0d,
	0xd6, 0x2a, 0xdc, 0x73, 0xa9, 0xa9, 0xd8, 0xaa, 0x1c, 0xd4, 0xaa, 0xad, 0xa8, 0x25, 0xee, 0xe7,
	0x6a, 0x3c, 0xb0, 0x2a, 0x8f, 0x93, 0x1f, 0x11, 0xf4, 0xf4, 0xcd, 0xe8, 0xa3, 0x33, 0x5d, 0x34,
	0x70, 0x7b, 0xd7, 0x06, 0xf4, 0xfa, 0xd9, 0x46, 0x86, 0x76, 0xeb, 0xd7, 0x46, 0xb4, 0xda, 0x74,
	0x33, 0xb4, 0x5d, 0xc0, 0x36, 0xa0, 0xd5, 0xb6, 0xa1, 0xa1, 0xed, 0x4c, 0x41, 0x24, 0xb9, 0x87,
	0x51, 0x73, 0xe3, 0xed, 0xf4, 0xe8, 0x6c, 0x78, 0x18, 0x4c, 0x8f, 0xce, 0x42, 0x83, 0xdb, 0xe9,
	0xd1, 0xef, 0xbf, 0x83, 0xc1, 0xf4, 0xe8, 0x5a, 0x37, 0x38, 0x79, 0x07, 0xa7, 0xe1, 0x57, 0xa0,
	0x2a, 0xf2, 0x02, 0xba, 0x92, 0x29, 0xf7, 0x38, 0x8e, 0x1e, 0x3a, 0x65, 0xaa, 0x2e, 0x90, 0x6a,
	0x7a, 0xf6, 0x15, 0x1e, 0xaf, 0xd3, 0xe2, 0xf6, 0x83, 0x26, 0x9a, 0xb7, 0xf5, 0xd1, 0xff, 0x2b,
	0x8b, 0xe5, 0x4a, 0xd7, 0x23, 0x17, 0xc7, 0xf2, 0xe0, 0xcb, 0x99, 0x4c, 0xfe, 0x45, 0xa9, 0x2a,
	0xf9, 0x6f, 0x13, 0x9b, 0x9f, 0xea, 0xed, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0x17, 0xeb,
	0xe1, 0xea, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TalkCloudLocationClient is the client API for TalkCloudLocation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TalkCloudLocationClient interface {
	// 上报设备数据
	ReportGPSData(ctx context.Context, in *ReportDataReq, opts ...grpc.CallOption) (*ReportDataResp, error)
}

type talkCloudLocationClient struct {
	cc *grpc.ClientConn
}

func NewTalkCloudLocationClient(cc *grpc.ClientConn) TalkCloudLocationClient {
	return &talkCloudLocationClient{cc}
}

func (c *talkCloudLocationClient) ReportGPSData(ctx context.Context, in *ReportDataReq, opts ...grpc.CallOption) (*ReportDataResp, error) {
	out := new(ReportDataResp)
	err := c.cc.Invoke(ctx, "/talk_cloud.TalkCloudLocation/ReportGPSData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TalkCloudLocationServer is the server API for TalkCloudLocation service.
type TalkCloudLocationServer interface {
	// 上报设备数据
	ReportGPSData(context.Context, *ReportDataReq) (*ReportDataResp, error)
}

// UnimplementedTalkCloudLocationServer can be embedded to have forward compatible implementations.
type UnimplementedTalkCloudLocationServer struct {
}

func (*UnimplementedTalkCloudLocationServer) ReportGPSData(ctx context.Context, req *ReportDataReq) (*ReportDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportGPSData not implemented")
}

func RegisterTalkCloudLocationServer(s *grpc.Server, srv TalkCloudLocationServer) {
	s.RegisterService(&_TalkCloudLocation_serviceDesc, srv)
}

func _TalkCloudLocation_ReportGPSData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkCloudLocationServer).ReportGPSData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/talk_cloud.TalkCloudLocation/ReportGPSData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkCloudLocationServer).ReportGPSData(ctx, req.(*ReportDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TalkCloudLocation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "talk_cloud.TalkCloudLocation",
	HandlerType: (*TalkCloudLocationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportGPSData",
			Handler:    _TalkCloudLocation_ReportGPSData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "talk_cloud_location.proto",
}
