// Code generated by protoc-gen-go. DO NOT EDIT.
// source: talk_cloud_location.proto

package talk_cloud

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GPSHttpReq struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Imei                 string   `protobuf:"bytes,2,opt,name=imei,proto3" json:"imei,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPSHttpReq) Reset()         { *m = GPSHttpReq{} }
func (m *GPSHttpReq) String() string { return proto.CompactTextString(m) }
func (*GPSHttpReq) ProtoMessage()    {}
func (*GPSHttpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{0}
}

func (m *GPSHttpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPSHttpReq.Unmarshal(m, b)
}
func (m *GPSHttpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPSHttpReq.Marshal(b, m, deterministic)
}
func (m *GPSHttpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPSHttpReq.Merge(m, src)
}
func (m *GPSHttpReq) XXX_Size() int {
	return xxx_messageInfo_GPSHttpReq.Size(m)
}
func (m *GPSHttpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GPSHttpReq.DiscardUnknown(m)
}

var xxx_messageInfo_GPSHttpReq proto.InternalMessageInfo

func (m *GPSHttpReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GPSHttpReq) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

type GPSHttpResp struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GpsInfo              *GPS     `protobuf:"bytes,2,opt,name=gpsInfo,proto3" json:"gpsInfo,omitempty"`
	Res                  *Result  `protobuf:"bytes,3,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPSHttpResp) Reset()         { *m = GPSHttpResp{} }
func (m *GPSHttpResp) String() string { return proto.CompactTextString(m) }
func (*GPSHttpResp) ProtoMessage()    {}
func (*GPSHttpResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{1}
}

func (m *GPSHttpResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPSHttpResp.Unmarshal(m, b)
}
func (m *GPSHttpResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPSHttpResp.Marshal(b, m, deterministic)
}
func (m *GPSHttpResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPSHttpResp.Merge(m, src)
}
func (m *GPSHttpResp) XXX_Size() int {
	return xxx_messageInfo_GPSHttpResp.Size(m)
}
func (m *GPSHttpResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GPSHttpResp.DiscardUnknown(m)
}

var xxx_messageInfo_GPSHttpResp proto.InternalMessageInfo

func (m *GPSHttpResp) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GPSHttpResp) GetGpsInfo() *GPS {
	if m != nil {
		return m.GpsInfo
	}
	return nil
}

func (m *GPSHttpResp) GetRes() *Result {
	if m != nil {
		return m.Res
	}
	return nil
}

// GPS 数据上报
type ReportDataReq struct {
	Uid                  int32     `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	IMei                 string    `protobuf:"bytes,2,opt,name=iMei,proto3" json:"iMei,omitempty"`
	DataType             int32     `protobuf:"varint,3,opt,name=dataType,proto3" json:"dataType,omitempty"`
	DeviceInfo           *Device   `protobuf:"bytes,4,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	LocationInfo         *Location `protobuf:"bytes,5,opt,name=locationInfo,proto3" json:"locationInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReportDataReq) Reset()         { *m = ReportDataReq{} }
func (m *ReportDataReq) String() string { return proto.CompactTextString(m) }
func (*ReportDataReq) ProtoMessage()    {}
func (*ReportDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{2}
}

func (m *ReportDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportDataReq.Unmarshal(m, b)
}
func (m *ReportDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportDataReq.Marshal(b, m, deterministic)
}
func (m *ReportDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportDataReq.Merge(m, src)
}
func (m *ReportDataReq) XXX_Size() int {
	return xxx_messageInfo_ReportDataReq.Size(m)
}
func (m *ReportDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReportDataReq proto.InternalMessageInfo

func (m *ReportDataReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ReportDataReq) GetIMei() string {
	if m != nil {
		return m.IMei
	}
	return ""
}

func (m *ReportDataReq) GetDataType() int32 {
	if m != nil {
		return m.DataType
	}
	return 0
}

func (m *ReportDataReq) GetDeviceInfo() *Device {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *ReportDataReq) GetLocationInfo() *Location {
	if m != nil {
		return m.LocationInfo
	}
	return nil
}

type Device struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceType           int32    `protobuf:"varint,2,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	Battery              int32    `protobuf:"varint,3,opt,name=battery,proto3" json:"battery,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{3}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Device) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *Device) GetBattery() int32 {
	if m != nil {
		return m.Battery
	}
	return 0
}

type Location struct {
	GpsInfo              *GPS         `protobuf:"bytes,1,opt,name=gpsInfo,proto3" json:"gpsInfo,omitempty"`
	BSInfo               *BaseStation `protobuf:"bytes,2,opt,name=bSInfo,proto3" json:"bSInfo,omitempty"`
	WifiInfo             *Wifi        `protobuf:"bytes,3,opt,name=wifiInfo,proto3" json:"wifiInfo,omitempty"`
	BtInfo               *BlueTooth   `protobuf:"bytes,4,opt,name=btInfo,proto3" json:"btInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{4}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetGpsInfo() *GPS {
	if m != nil {
		return m.GpsInfo
	}
	return nil
}

func (m *Location) GetBSInfo() *BaseStation {
	if m != nil {
		return m.BSInfo
	}
	return nil
}

func (m *Location) GetWifiInfo() *Wifi {
	if m != nil {
		return m.WifiInfo
	}
	return nil
}

func (m *Location) GetBtInfo() *BlueTooth {
	if m != nil {
		return m.BtInfo
	}
	return nil
}

type GPS struct {
	LocalTime            uint64   `protobuf:"varint,1,opt,name=localTime,proto3" json:"localTime,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Speed                float32  `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Course               float32  `protobuf:"fixed32,5,opt,name=course,proto3" json:"course,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPS) Reset()         { *m = GPS{} }
func (m *GPS) String() string { return proto.CompactTextString(m) }
func (*GPS) ProtoMessage()    {}
func (*GPS) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{5}
}

func (m *GPS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPS.Unmarshal(m, b)
}
func (m *GPS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPS.Marshal(b, m, deterministic)
}
func (m *GPS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPS.Merge(m, src)
}
func (m *GPS) XXX_Size() int {
	return xxx_messageInfo_GPS.Size(m)
}
func (m *GPS) XXX_DiscardUnknown() {
	xxx_messageInfo_GPS.DiscardUnknown(m)
}

var xxx_messageInfo_GPS proto.InternalMessageInfo

func (m *GPS) GetLocalTime() uint64 {
	if m != nil {
		return m.LocalTime
	}
	return 0
}

func (m *GPS) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *GPS) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GPS) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *GPS) GetCourse() float32 {
	if m != nil {
		return m.Course
	}
	return 0
}

type BaseStation struct {
	Country              int32    `protobuf:"varint,1,opt,name=country,proto3" json:"country,omitempty"`
	Operator             int32    `protobuf:"varint,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Lac                  int32    `protobuf:"varint,3,opt,name=lac,proto3" json:"lac,omitempty"`
	Cid                  int32    `protobuf:"varint,4,opt,name=cid,proto3" json:"cid,omitempty"`
	FirstBs              int32    `protobuf:"varint,5,opt,name=firstBs,proto3" json:"firstBs,omitempty"`
	SecondBs             int32    `protobuf:"varint,6,opt,name=secondBs,proto3" json:"secondBs,omitempty"`
	ThirdBs              int32    `protobuf:"varint,7,opt,name=thirdBs,proto3" json:"thirdBs,omitempty"`
	FourthBs             int32    `protobuf:"varint,8,opt,name=fourthBs,proto3" json:"fourthBs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseStation) Reset()         { *m = BaseStation{} }
func (m *BaseStation) String() string { return proto.CompactTextString(m) }
func (*BaseStation) ProtoMessage()    {}
func (*BaseStation) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{6}
}

func (m *BaseStation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseStation.Unmarshal(m, b)
}
func (m *BaseStation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseStation.Marshal(b, m, deterministic)
}
func (m *BaseStation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseStation.Merge(m, src)
}
func (m *BaseStation) XXX_Size() int {
	return xxx_messageInfo_BaseStation.Size(m)
}
func (m *BaseStation) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseStation.DiscardUnknown(m)
}

var xxx_messageInfo_BaseStation proto.InternalMessageInfo

func (m *BaseStation) GetCountry() int32 {
	if m != nil {
		return m.Country
	}
	return 0
}

func (m *BaseStation) GetOperator() int32 {
	if m != nil {
		return m.Operator
	}
	return 0
}

func (m *BaseStation) GetLac() int32 {
	if m != nil {
		return m.Lac
	}
	return 0
}

func (m *BaseStation) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *BaseStation) GetFirstBs() int32 {
	if m != nil {
		return m.FirstBs
	}
	return 0
}

func (m *BaseStation) GetSecondBs() int32 {
	if m != nil {
		return m.SecondBs
	}
	return 0
}

func (m *BaseStation) GetThirdBs() int32 {
	if m != nil {
		return m.ThirdBs
	}
	return 0
}

func (m *BaseStation) GetFourthBs() int32 {
	if m != nil {
		return m.FourthBs
	}
	return 0
}

// TODO 待定
type Wifi struct {
	FirstWifi            int32    `protobuf:"varint,1,opt,name=firstWifi,proto3" json:"firstWifi,omitempty"`
	SecondWifi           int32    `protobuf:"varint,2,opt,name=secondWifi,proto3" json:"secondWifi,omitempty"`
	ThirdWifi            int32    `protobuf:"varint,3,opt,name=thirdWifi,proto3" json:"thirdWifi,omitempty"`
	FourthWifi           int32    `protobuf:"varint,4,opt,name=fourthWifi,proto3" json:"fourthWifi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wifi) Reset()         { *m = Wifi{} }
func (m *Wifi) String() string { return proto.CompactTextString(m) }
func (*Wifi) ProtoMessage()    {}
func (*Wifi) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{7}
}

func (m *Wifi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wifi.Unmarshal(m, b)
}
func (m *Wifi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wifi.Marshal(b, m, deterministic)
}
func (m *Wifi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wifi.Merge(m, src)
}
func (m *Wifi) XXX_Size() int {
	return xxx_messageInfo_Wifi.Size(m)
}
func (m *Wifi) XXX_DiscardUnknown() {
	xxx_messageInfo_Wifi.DiscardUnknown(m)
}

var xxx_messageInfo_Wifi proto.InternalMessageInfo

func (m *Wifi) GetFirstWifi() int32 {
	if m != nil {
		return m.FirstWifi
	}
	return 0
}

func (m *Wifi) GetSecondWifi() int32 {
	if m != nil {
		return m.SecondWifi
	}
	return 0
}

func (m *Wifi) GetThirdWifi() int32 {
	if m != nil {
		return m.ThirdWifi
	}
	return 0
}

func (m *Wifi) GetFourthWifi() int32 {
	if m != nil {
		return m.FourthWifi
	}
	return 0
}

//TODO 待定
type BlueTooth struct {
	FirstBt              int32    `protobuf:"varint,1,opt,name=firstBt,proto3" json:"firstBt,omitempty"`
	SecondBt             int32    `protobuf:"varint,2,opt,name=secondBt,proto3" json:"secondBt,omitempty"`
	ThirdBt              int32    `protobuf:"varint,3,opt,name=thirdBt,proto3" json:"thirdBt,omitempty"`
	FourthBt             int32    `protobuf:"varint,4,opt,name=fourthBt,proto3" json:"fourthBt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlueTooth) Reset()         { *m = BlueTooth{} }
func (m *BlueTooth) String() string { return proto.CompactTextString(m) }
func (*BlueTooth) ProtoMessage()    {}
func (*BlueTooth) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{8}
}

func (m *BlueTooth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlueTooth.Unmarshal(m, b)
}
func (m *BlueTooth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlueTooth.Marshal(b, m, deterministic)
}
func (m *BlueTooth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlueTooth.Merge(m, src)
}
func (m *BlueTooth) XXX_Size() int {
	return xxx_messageInfo_BlueTooth.Size(m)
}
func (m *BlueTooth) XXX_DiscardUnknown() {
	xxx_messageInfo_BlueTooth.DiscardUnknown(m)
}

var xxx_messageInfo_BlueTooth proto.InternalMessageInfo

func (m *BlueTooth) GetFirstBt() int32 {
	if m != nil {
		return m.FirstBt
	}
	return 0
}

func (m *BlueTooth) GetSecondBt() int32 {
	if m != nil {
		return m.SecondBt
	}
	return 0
}

func (m *BlueTooth) GetThirdBt() int32 {
	if m != nil {
		return m.ThirdBt
	}
	return 0
}

func (m *BlueTooth) GetFourthBt() int32 {
	if m != nil {
		return m.FourthBt
	}
	return 0
}

type ReportDataResp struct {
	Res                  *Result  `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportDataResp) Reset()         { *m = ReportDataResp{} }
func (m *ReportDataResp) String() string { return proto.CompactTextString(m) }
func (*ReportDataResp) ProtoMessage()    {}
func (*ReportDataResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d4a30cba502519, []int{9}
}

func (m *ReportDataResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportDataResp.Unmarshal(m, b)
}
func (m *ReportDataResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportDataResp.Marshal(b, m, deterministic)
}
func (m *ReportDataResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportDataResp.Merge(m, src)
}
func (m *ReportDataResp) XXX_Size() int {
	return xxx_messageInfo_ReportDataResp.Size(m)
}
func (m *ReportDataResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportDataResp.DiscardUnknown(m)
}

var xxx_messageInfo_ReportDataResp proto.InternalMessageInfo

func (m *ReportDataResp) GetRes() *Result {
	if m != nil {
		return m.Res
	}
	return nil
}

func init() {
	proto.RegisterType((*GPSHttpReq)(nil), "talk_cloud.GPSHttpReq")
	proto.RegisterType((*GPSHttpResp)(nil), "talk_cloud.GPSHttpResp")
	proto.RegisterType((*ReportDataReq)(nil), "talk_cloud.ReportDataReq")
	proto.RegisterType((*Device)(nil), "talk_cloud.Device")
	proto.RegisterType((*Location)(nil), "talk_cloud.Location")
	proto.RegisterType((*GPS)(nil), "talk_cloud.GPS")
	proto.RegisterType((*BaseStation)(nil), "talk_cloud.BaseStation")
	proto.RegisterType((*Wifi)(nil), "talk_cloud.Wifi")
	proto.RegisterType((*BlueTooth)(nil), "talk_cloud.BlueTooth")
	proto.RegisterType((*ReportDataResp)(nil), "talk_cloud.ReportDataResp")
}

func init() { proto.RegisterFile("talk_cloud_location.proto", fileDescriptor_24d4a30cba502519) }

var fileDescriptor_24d4a30cba502519 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcb, 0x4e, 0x14, 0x4d,
	0x14, 0xfe, 0xbb, 0xe7, 0xc2, 0x70, 0xe0, 0x47, 0xa8, 0x20, 0x0c, 0x13, 0x63, 0x48, 0xc7, 0x05,
	0x26, 0x0a, 0xc9, 0x98, 0x18, 0xd7, 0x23, 0xc9, 0x60, 0x22, 0xc9, 0x58, 0x33, 0x89, 0x4b, 0x52,
	0xd3, 0x5d, 0x03, 0x15, 0x9a, 0xae, 0xb2, 0xab, 0x5a, 0x42, 0x8c, 0x1b, 0xb6, 0x2e, 0x7d, 0x11,
	0xdf, 0xc0, 0x85, 0x8f, 0xc0, 0x2b, 0xf8, 0x20, 0xa6, 0x6e, 0xdd, 0x85, 0x82, 0xee, 0xfa, 0x3b,
	0xdf, 0xf9, 0xce, 0xb5, 0xfa, 0xc0, 0x8e, 0x22, 0xf9, 0xf9, 0x49, 0x9a, 0xf3, 0x2a, 0x3b, 0xc9,
	0x79, 0x4a, 0x14, 0xe3, 0xc5, 0xbe, 0x28, 0xb9, 0xe2, 0x08, 0x1a, 0x6a, 0xb0, 0x15, 0xb8, 0x5d,
	0xf0, 0x8c, 0xe6, 0xd6, 0x67, 0xb0, 0x41, 0x8a, 0x82, 0x2b, 0xa3, 0x92, 0xd6, 0x94, 0x0c, 0x01,
	0xc6, 0x93, 0xe9, 0x91, 0x52, 0x02, 0xd3, 0x0f, 0x68, 0x1d, 0x5a, 0x15, 0xcb, 0xfa, 0xd1, 0x6e,
	0xb4, 0xd7, 0xc1, 0xfa, 0x13, 0x21, 0x68, 0xb3, 0x0b, 0xca, 0xfa, 0xf1, 0x6e, 0xb4, 0xb7, 0x8c,
	0xcd, 0x77, 0x22, 0x60, 0xa5, 0xd6, 0x48, 0x71, 0x87, 0xe8, 0x29, 0x2c, 0x9d, 0x0a, 0xf9, 0xa6,
	0x58, 0x70, 0xa3, 0x5b, 0x19, 0x3e, 0xd8, 0x6f, 0x2a, 0xda, 0x1f, 0x4f, 0xa6, 0xd8, 0xf3, 0xe8,
	0x09, 0xb4, 0x4a, 0x2a, 0xfb, 0x2d, 0xe3, 0x86, 0x42, 0x37, 0x4c, 0x65, 0x95, 0x2b, 0xac, 0xe9,
	0xe4, 0x7b, 0x04, 0xff, 0x63, 0x2a, 0x78, 0xa9, 0x0e, 0x89, 0x22, 0xf7, 0x57, 0x7a, 0x1c, 0x54,
	0x7a, 0x4c, 0x19, 0x1a, 0x40, 0x2f, 0x23, 0x8a, 0xcc, 0xae, 0x04, 0x35, 0x29, 0x3a, 0xb8, 0xc6,
	0x68, 0x08, 0x90, 0xd1, 0x8f, 0x2c, 0xa5, 0xa6, 0xce, 0xf6, 0x9f, 0x05, 0x1c, 0x1a, 0x16, 0x07,
	0x5e, 0xe8, 0x15, 0xac, 0xfa, 0xb1, 0x1b, 0x55, 0xc7, 0xa8, 0x36, 0x43, 0xd5, 0x5b, 0xc7, 0xe3,
	0x5b, 0x9e, 0x09, 0x86, 0xae, 0x8d, 0x87, 0xd6, 0x20, 0xae, 0x0b, 0x8f, 0x59, 0x86, 0x1e, 0xfb,
	0x3a, 0x4c, 0x95, 0xb1, 0xb1, 0x07, 0x16, 0xd4, 0x87, 0xa5, 0x39, 0x51, 0x8a, 0x96, 0x57, 0xae,
	0x05, 0x0f, 0x93, 0x1f, 0x11, 0xf4, 0x7c, 0xba, 0x70, 0xe6, 0xd1, 0x3f, 0x66, 0x7e, 0x00, 0xdd,
	0xf9, 0x34, 0xd8, 0xce, 0x76, 0xe8, 0x39, 0x22, 0x92, 0x4e, 0xed, 0x1b, 0xc1, 0xce, 0x0d, 0x3d,
	0x83, 0xde, 0x25, 0x5b, 0x30, 0x23, 0xb1, 0x9b, 0x5a, 0x0f, 0x25, 0xef, 0xd9, 0x82, 0xe1, 0xda,
	0x03, 0x3d, 0x87, 0xee, 0x5c, 0x05, 0x43, 0x7d, 0x78, 0x2b, 0x7c, 0x5e, 0xd1, 0x19, 0xe7, 0xea,
	0x0c, 0x3b, 0xa7, 0xe4, 0x4b, 0x04, 0xad, 0xf1, 0x64, 0x8a, 0x1e, 0xc1, 0xb2, 0x9e, 0x58, 0x3e,
	0x63, 0x17, 0xd4, 0xb4, 0xd0, 0xc6, 0x8d, 0xc1, 0xb2, 0xc5, 0x29, 0x53, 0x55, 0x66, 0x87, 0x14,
	0xe1, 0xc6, 0xa0, 0xf7, 0x9c, 0x13, 0x65, 0xc9, 0x96, 0x21, 0x6b, 0x8c, 0x36, 0xa1, 0x23, 0x05,
	0xa5, 0x99, 0xa9, 0x26, 0xc6, 0x16, 0xa0, 0x2d, 0xe8, 0xa6, 0xbc, 0x2a, 0x25, 0x35, 0x3b, 0x8c,
	0xb1, 0x43, 0xc9, 0x4d, 0x04, 0x2b, 0xc1, 0x08, 0xf4, 0xf4, 0x53, 0x5e, 0x15, 0xaa, 0xbc, 0x72,
	0x2b, 0xf3, 0x50, 0xe7, 0xe4, 0x82, 0x96, 0x44, 0xf1, 0xd2, 0x6d, 0xad, 0xc6, 0xfa, 0x75, 0xe6,
	0x24, 0x75, 0xfb, 0xd2, 0x9f, 0xda, 0x92, 0x32, 0x5b, 0x43, 0x07, 0xeb, 0x4f, 0x1d, 0x79, 0xc1,
	0x4a, 0xa9, 0x46, 0xd2, 0x94, 0xd0, 0xc1, 0x1e, 0xea, 0xc8, 0x92, 0xa6, 0xbc, 0xc8, 0x46, 0xb2,
	0xdf, 0xb5, 0x91, 0x3d, 0xd6, 0x2a, 0x75, 0xc6, 0x4a, 0x4d, 0x2d, 0x59, 0x95, 0x83, 0x5a, 0xb5,
	0xe0, 0x55, 0xa9, 0xce, 0x46, 0xb2, 0xdf, 0xb3, 0x2a, 0x8f, 0x93, 0xeb, 0x08, 0xda, 0x7a, 0x4b,
	0x7a, 0x8c, 0x26, 0x8b, 0x06, 0xae, 0xa1, 0xc6, 0xa0, 0x9f, 0xa2, 0x4d, 0x64, 0x68, 0xf7, 0x14,
	0x1b, 0x8b, 0x56, 0x9b, 0x6c, 0x86, 0xb6, 0xcd, 0x35, 0x06, 0xad, 0xb6, 0x09, 0x0d, 0x6d, 0x3b,
	0x0d, 0x2c, 0xc9, 0x25, 0x2c, 0xd7, 0xdb, 0x6f, 0xba, 0x57, 0x7e, 0xae, 0x0e, 0x06, 0xdd, 0x2b,
	0x3f, 0x57, 0x8f, 0x9b, 0xee, 0x95, 0xff, 0x17, 0x1c, 0x0c, 0xba, 0x57, 0x2e, 0x75, 0x8d, 0x93,
	0x97, 0xb0, 0x16, 0x1e, 0x0f, 0x29, 0xfc, 0xd5, 0x89, 0xfe, 0x7a, 0x75, 0x86, 0xdf, 0x22, 0xd8,
	0x98, 0x91, 0xfc, 0xfc, 0xb5, 0x66, 0xea, 0x1f, 0xed, 0xc8, 0x9f, 0xa2, 0xf1, 0x64, 0xaa, 0x03,
	0xa2, 0x9d, 0xdb, 0xfa, 0xe0, 0x4a, 0x0d, 0x06, 0xf7, 0x51, 0x52, 0x24, 0xff, 0xa1, 0x77, 0x00,
	0x63, 0xaa, 0xc6, 0x42, 0x9a, 0x30, 0x5b, 0xbf, 0xfd, 0xaf, 0xee, 0x26, 0x0f, 0xb6, 0xef, 0xb4,
	0x4b, 0x91, 0xa0, 0xeb, 0x9b, 0x9f, 0x5f, 0xe3, 0x55, 0x04, 0x07, 0xa7, 0x42, 0x1e, 0x7c, 0xaa,
	0x58, 0xf6, 0x79, 0xde, 0x35, 0x57, 0xfd, 0xc5, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x9c,
	0xe5, 0xb0, 0x29, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TalkCloudLocationClient is the client API for TalkCloudLocation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TalkCloudLocationClient interface {
	// 上报设备数据
	ReportGPSData(ctx context.Context, in *ReportDataReq, opts ...grpc.CallOption) (*ReportDataResp, error)
	// 返回gps数据
	GetGpsData(ctx context.Context, in *GPSHttpReq, opts ...grpc.CallOption) (*GPSHttpResp, error)
}

type talkCloudLocationClient struct {
	cc *grpc.ClientConn
}

func NewTalkCloudLocationClient(cc *grpc.ClientConn) TalkCloudLocationClient {
	return &talkCloudLocationClient{cc}
}

func (c *talkCloudLocationClient) ReportGPSData(ctx context.Context, in *ReportDataReq, opts ...grpc.CallOption) (*ReportDataResp, error) {
	out := new(ReportDataResp)
	err := c.cc.Invoke(ctx, "/talk_cloud.TalkCloudLocation/ReportGPSData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talkCloudLocationClient) GetGpsData(ctx context.Context, in *GPSHttpReq, opts ...grpc.CallOption) (*GPSHttpResp, error) {
	out := new(GPSHttpResp)
	err := c.cc.Invoke(ctx, "/talk_cloud.TalkCloudLocation/GetGpsData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TalkCloudLocationServer is the server API for TalkCloudLocation service.
type TalkCloudLocationServer interface {
	// 上报设备数据
	ReportGPSData(context.Context, *ReportDataReq) (*ReportDataResp, error)
	// 返回gps数据
	GetGpsData(context.Context, *GPSHttpReq) (*GPSHttpResp, error)
}

// UnimplementedTalkCloudLocationServer can be embedded to have forward compatible implementations.
type UnimplementedTalkCloudLocationServer struct {
}

func (*UnimplementedTalkCloudLocationServer) ReportGPSData(ctx context.Context, req *ReportDataReq) (*ReportDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportGPSData not implemented")
}
func (*UnimplementedTalkCloudLocationServer) GetGpsData(ctx context.Context, req *GPSHttpReq) (*GPSHttpResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGpsData not implemented")
}

func RegisterTalkCloudLocationServer(s *grpc.Server, srv TalkCloudLocationServer) {
	s.RegisterService(&_TalkCloudLocation_serviceDesc, srv)
}

func _TalkCloudLocation_ReportGPSData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkCloudLocationServer).ReportGPSData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/talk_cloud.TalkCloudLocation/ReportGPSData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkCloudLocationServer).ReportGPSData(ctx, req.(*ReportDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalkCloudLocation_GetGpsData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GPSHttpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkCloudLocationServer).GetGpsData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/talk_cloud.TalkCloudLocation/GetGpsData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkCloudLocationServer).GetGpsData(ctx, req.(*GPSHttpReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TalkCloudLocation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "talk_cloud.TalkCloudLocation",
	HandlerType: (*TalkCloudLocationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportGPSData",
			Handler:    _TalkCloudLocation_ReportGPSData_Handler,
		},
		{
			MethodName: "GetGpsData",
			Handler:    _TalkCloudLocation_GetGpsData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "talk_cloud_location.proto",
}
